{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.backend_protocol | default "HTTP" }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.group_name | default "default" }}
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds={{ .Values.ingress.tg_attributes_deregistration_delay | default "90" }}
    {{- if .Values.ingress.public }}
    {{- if .Values.create_dns_records }}
    external-dns-private: "true"
    external-dns-public: "true"
    {{- end }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ingress.lb_inbound_cidrs | default "0.0.0.0/0" }}
    {{- else }}
    {{- if .Values.create_dns_records }}
    external-dns-private: "true"
    {{- end }}
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ingress.lb_inbound_cidrs | default "10.0.0.0/8" }}
    {{- end }}
    alb.ingress.kubernetes.io/target-type: ip
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.ingress.listeners | default "[{\"HTTP\":80}, {\"HTTPS\":443}]" }}'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-policy: {{ .Values.ingress.lb_ssl_policy | default "ELBSecurityPolicy-TLS13-1-2-2021-06" }}
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '{{ .Values.ingress.listeners | default "[{\"HTTP\":80}]" }}'
    {{- end }}
    {{- if .Values.ingress.lb_name }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.lb_name }}
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true{{ if .Values.ingress.lb_logs_s3_bucket }},access_logs.s3.enabled=true,access_logs.s3.bucket={{ .Values.ingress.lb_logs_s3_bucket }}{{- if .Values.ingress.lb_name }},access_logs.s3.prefix={{ .Values.ingress.lb_name }}{{ end }}{{ end }}{{ if .Values.ingress.lb_deletion_protection }},deletion_protection.enabled=true{{ end }}{{ if .Values.ingress.lb_timeout }},idle_timeout.timeout_seconds={{ .Values.ingress.lb_timeout }}{{ end }}{{ if .Values.ingress.lb_waf_fail_open }},waf.fail_open.enabled=true{{ end }}
    {{- end }}
    {{- if .Values.ingress.redirect_path }}
    {{- range .Values.ingress.hosts }}
    alb.ingress.kubernetes.io/actions.redirect: '{"type":"redirect","redirectConfig":{"host":"{{ . }}","path":"{{ $.Values.ingress.redirect_path }}","port":"443","protocol":"HTTPS","query":"","statusCode":"HTTP_302"}}'
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.waf_acl_id }}
    alb.ingress.kubernetes.io/waf-acl-id: {{ .Values.ingress.waf_acl_id }}
    {{- end }}
    {{- if .Values.ingress.waf_acl_arn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.waf_acl_arn }}
    {{- end }}
    {{- if .Values.ingress.public }}
    alb.ingress.kubernetes.io/tags: 'Purpose=External_LB'
    {{- else }}
    alb.ingress.kubernetes.io/tags: 'Purpose=Internal_LB'
    {{- end }}

  labels:
    app.kubernetes.io/name: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  ingressClassName: alb
  rules:
  {{- $context1 := . }}
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    {{- with $context1 }}
    http:
      paths:
      {{- if .Values.ingress.redirect_path }}
      - backend:
          service:
            name: redirect
            port:
              name: use-annotation
        path: /
        pathType: Exact
      {{- end }}
      - backend:
          service:
            name: {{ .Values.name }}
            port:
              number: 80
        path: /
        pathType: Prefix
    {{- end }}
  {{- end }}
---
{{- end }}
