{{- $pull_secrets := dict -}}
{{- range .Values.imagePullSecrets -}}
{{- if not (hasKey $pull_secrets .k8s_secret_name) -}}
{{- $_ := set $pull_secrets .k8s_secret_name .aws_secret_name -}}
{{- end -}}
{{- end -}}
{{- range .Values.secretInitDeployment.imagePullSecrets -}}
{{- if not (hasKey $pull_secrets .k8s_secret_name) -}}
{{- $_ := set $pull_secrets .k8s_secret_name .aws_secret_name -}}
{{- end -}}
{{- end -}}

{{- range $dict_key, $dict_value := $pull_secrets -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $dict_key }}
spec:
  provider: aws
  secretObjects:
  - data:
    - key: ".dockerconfigjson"
      objectName: "secret"
    secretName: {{ $dict_key }}
    type: kubernetes.io/dockerconfigjson
  parameters:
    objects: |
        - objectName: {{ $dict_value }}
          objectType: "secretsmanager"
          objectAlias: "secret"
---
{{- end }}

{{- $env_secrets := dict -}}
{{- range .Values.envSecrets -}}
  {{- if not (hasKey $env_secrets .k8s_secret_name) -}}
    {{- $_ := set $env_secrets .k8s_secret_name (dict "aws_secret_name" .aws_secret_name "keys" (or .keys list) "variable_name" .variable_name) -}}
  {{- end -}}
{{- end -}}

{{- range $dict_key, $dict_value := $env_secrets -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $dict_key }}
spec:
  provider: aws
  secretObjects:
  - data:
    {{- if and $dict_value.keys (gt (len $dict_value.keys) 0) }}
      {{- range $dict_value.keys }}
    - key: "{{ . }}"
      objectName: "{{ . }}"
      {{- end }}
    {{- else }}
    - key: "secret"
      objectName: "secret"
    {{- end }}
    secretName: {{ $dict_key }}
    type: Opaque
  parameters:
    objects: |
    {{- if and $dict_value.keys (gt (len $dict_value.keys) 0) }}
      - objectName: {{ $dict_value.aws_secret_name }}
        objectType: "secretsmanager"
        jmesPath:
        {{- range $dict_value.keys }}
          - path: "{{ . }}"
            objectAlias: "{{ . }}"
        {{- end }}
    {{- else }}
      - objectName: {{ $dict_value.aws_secret_name }}
        objectType: "secretsmanager"
        objectAlias: "secret"
    {{- end }}
---
{{- end }}
