{{- if and .Values.image .Values.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  {{- if and .Values.service .Values.service.annotations }}
  annotations:
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
---
{{- end }}
